apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: result-dev-eva
  annotations:
    codefresh.io/product: result
spec:
  project: default
  destination:
    namespace: eva-development
    server: https://kubernetes.default.svc
  sources:
    - path: environments/development/result
      repoURL: https://github.com/salesdemocf/configs.git
      targetRevision: HEAD
      helm:
        values: null
        valueFiles:
          - values.yaml
        parameters: null
    - ref: common-values
      repoURL: https://github.com/salesdemocf/configs.git
      targetRevision: HEAD
  syncPolicy:
    syncOptions:
      - PrunePropagationPolicy=foreground
      - Replace=false
      - PruneLast=false
      - Validate=true
      - CreateNamespace=false
      - ApplyOutOfSyncOnly=false
      - ServerSideApply=true
      - RespectIgnoreDifferences=false
