apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: result-prod-eva
  annotations:
    codefresh.io/product: result
spec:
  project: default
  sources:
  - repoURL: https://github.com/salesdemocf/configs.git
    targetRevision: HEAD
    path: environments/production/result
    helm:
      valueFiles:
      - values.yaml
      - $common-values/common/result/values.yaml
  - repoURL: https://github.com/salesdemocf/configs.git
    targetRevision: HEAD
    ref: common-values
  destination:
    namespace: eva-production
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      allowEmpty: true
      prune: true
      selfHeal: true
    syncOptions:
      - Validate=false
      - CreateNamespace=true
